import { WorkerTelemetry, HardwareSensor, SafetyAlert } from '@/types/telemetry';
import { calculateWorkerStatus } from './thresholds';

// Generate 12 historical 5-minute data points for the last 1 hour
function generateHistory(baseH2S: number, baseHR: number, baseTemp: number, basePM: number, baseRad: number) {
  const times = ['17:10', '17:15', '17:20', '17:25', '17:30', '17:35', '17:40', '17:45', '17:50', '17:55', '18:00', '18:05'];
  return times.map((t, idx) => {
    // gentle variance along the trend
    const varianceFactor = Math.sin(idx / 2) * 0.15;
    return {
      time: t,
      h2s: Number((baseH2S + varianceFactor * 0.8).toFixed(2)),
      heartRate: Math.round(baseHR + Math.cos(idx / 1.5) * 4),
      temperature: Number((baseTemp + varianceFactor * 0.4).toFixed(1)),
      humidity: Math.round(78 + Math.sin(idx) * 3),
      pm25: Number((basePM + Math.sin(idx * 1.2) * 4).toFixed(1)),
      radiationUSv: Number((baseRad + (Math.random() - 0.5) * 0.02).toFixed(2)),
    };
  });
}

export const initialWorkers: WorkerTelemetry[] = [
  {
    id: 'W1024',
    name: 'Ramesh Verma',
    jacketId: 'SJ-001',
    role: 'Excavation Lead',
    zone: 'Shaft 3 - Level 4 Coal Face',
    status: 'online',
    h2s: 1.8,
    heartRate: 76,
    temperature: 28.4,
    humidity: 76,
    pm25: 22.4,
    radiationCPM: 22,
    radiationUSv: 0.18,
    battery: 92,
    loraRSSI: -72,
    loraSNR: 9.4,
    uwbX: 42.5,
    uwbY: 118.2,
    pcmCoolingStatus: 'Active Cooling (18°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: 'Just now',
    history: generateHistory(1.8, 76, 28.4, 22.4, 0.18),
  },
  {
    id: 'W1025',
    name: 'Sunil Sharma',
    jacketId: 'SJ-002',
    role: 'Blaster Tech',
    zone: 'Tunnel 2 - Heading East',
    status: 'warning',
    h2s: 6.4, // Warning (> 5.0)
    heartRate: 114, // Warning (> 100)
    temperature: 34.8,
    humidity: 82,
    pm25: 41.2,
    radiationCPM: 28,
    radiationUSv: 0.23,
    battery: 68,
    loraRSSI: -84,
    loraSNR: 7.1,
    uwbX: 84.1,
    uwbY: 62.0,
    pcmCoolingStatus: 'Partially Depleted (25°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: '2s ago',
    history: generateHistory(6.4, 114, 34.8, 41.2, 0.23),
  },
  {
    id: 'W1026',
    name: 'Underground Worker',
    jacketId: 'SJ-003',
    role: 'Drill Operator',
    zone: 'Deep Incline Shaft 4',
    status: 'online',
    h2s: 2.1,
    heartRate: 78,
    temperature: 29.1,
    humidity: 74,
    pm25: 28.0,
    radiationCPM: 20,
    radiationUSv: 0.16,
    battery: 88,
    loraRSSI: -68,
    loraSNR: 10.2,
    uwbX: 112.4,
    uwbY: 204.8,
    pcmCoolingStatus: 'Active Cooling (18°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: 'Just now',
    history: generateHistory(2.1, 78, 29.1, 28.0, 0.16),
  },
  {
    id: 'W1027',
    name: 'Alok Mukherjee',
    jacketId: 'SJ-004',
    role: 'Safety Inspector',
    zone: 'Shaft 1 - Main Intake Drift',
    status: 'online',
    h2s: 0.4,
    heartRate: 70,
    temperature: 26.2,
    humidity: 68,
    pm25: 14.5,
    radiationCPM: 16,
    radiationUSv: 0.13,
    battery: 96,
    loraRSSI: -62,
    loraSNR: 11.5,
    uwbX: 18.0,
    uwbY: 45.3,
    pcmCoolingStatus: 'Nominal (21°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: 'Just now',
    history: generateHistory(0.4, 70, 26.2, 14.5, 0.13),
  },
  {
    id: 'W1028',
    name: 'Manoj Yadav',
    jacketId: 'SJ-005',
    role: 'Conveyor Tech',
    zone: 'Level 4 - Sump & Drainage',
    status: 'critical',
    h2s: 11.8, // Critical (> 10.0 ppm)
    heartRate: 128, // Critical (> 120 bpm)
    temperature: 38.6, // Critical (> 38.0°C)
    humidity: 89,
    pm25: 58.0,
    radiationCPM: 34,
    radiationUSv: 0.28,
    battery: 42,
    loraRSSI: -91,
    loraSNR: 4.8,
    uwbX: 156.2,
    uwbY: 312.0,
    pcmCoolingStatus: 'Exhausted (28°C)',
    sosActive: false,
    colorimetricH2SDetected: true, // Optical strip confirmed dark brown stain
    lastPing: '1s ago',
    history: generateHistory(11.8, 128, 38.6, 58.0, 0.28),
  },
  {
    id: 'W1029',
    name: 'Kishan Murmu',
    jacketId: 'SJ-006',
    role: 'Support Rigging',
    zone: 'Tunnel 3 - Ventilation Return',
    status: 'online',
    h2s: 3.2,
    heartRate: 82,
    temperature: 31.0,
    humidity: 80,
    pm25: 31.5,
    radiationCPM: 24,
    radiationUSv: 0.20,
    battery: 84,
    loraRSSI: -76,
    loraSNR: 8.9,
    uwbX: 68.3,
    uwbY: 145.7,
    pcmCoolingStatus: 'Active Cooling (18°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: 'Just now',
    history: generateHistory(3.2, 82, 31.0, 31.5, 0.20),
  },
  {
    id: 'W1030',
    name: 'Deepak Soren',
    jacketId: 'SJ-007',
    role: 'Roof Bolter',
    zone: 'Shaft 5 - Rock Bolt Decline',
    status: 'warning',
    h2s: 2.8,
    heartRate: 98,
    temperature: 32.5,
    humidity: 85,
    pm25: 52.8, // Warning (> 35.0)
    radiationCPM: 26,
    radiationUSv: 0.21,
    battery: 74,
    loraRSSI: -82,
    loraSNR: 7.6,
    uwbX: 94.0,
    uwbY: 220.5,
    pcmCoolingStatus: 'Partially Depleted (25°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: '3s ago',
    history: generateHistory(2.8, 98, 32.5, 52.8, 0.21),
  },
  {
    id: 'W1031',
    name: 'Tsering Dorje',
    jacketId: 'SJ-008',
    role: 'Geotech Tech',
    zone: 'Deep Strata Core Station',
    status: 'online',
    h2s: 1.1,
    heartRate: 72,
    temperature: 27.8,
    humidity: 71,
    pm25: 18.2,
    radiationCPM: 38, // Elevated but safe (< 0.60)
    radiationUSv: 0.31,
    battery: 94,
    loraRSSI: -70,
    loraSNR: 9.8,
    uwbX: 138.6,
    uwbY: 88.4,
    pcmCoolingStatus: 'Nominal (21°C)',
    sosActive: false,
    colorimetricH2SDetected: false,
    lastPing: 'Just now',
    history: generateHistory(1.1, 72, 27.8, 18.2, 0.31),
  },
];

// Strictly restricted hardware components
export const initialSensors: HardwareSensor[] = [
  {
    id: 'SENS-H2S-E',
    name: 'H2S Electronic Sensor',
    model: 'SPEC 3SP_H2S_50',
    type: 'gas',
    value: 11.8,
    unit: 'ppm',
    status: 'critical',
    zone: 'Level 4 - Sump (SJ-005)',
    hardwareSpecs: 'Range 0-50 ppm, Resolution 0.01 ppm, Response < 15s (Amperometric Gas Sensor)',
    trend: [
      { time: '17:15', value: 2.1 },
      { time: '17:30', value: 4.8 },
      { time: '17:45', value: 8.2 },
      { time: '18:00', value: 11.8 },
    ],
  },
  {
    id: 'SENS-H2S-OPT',
    name: 'Colorimetric H2S Strip + Camera',
    model: 'OV2640 Optical Strip Analyzer',
    type: 'gas',
    value: 'Positive (Darkened Stain)',
    unit: 'PbAc Optical Index',
    status: 'critical',
    zone: 'Chest Lapel Array (SJ-005)',
    hardwareSpecs: 'Lead Acetate paper test with ESP32-CAM optical HSV colorimetric verification',
    trend: [
      { time: '17:15', value: 0.05 },
      { time: '17:30', value: 0.22 },
      { time: '17:45', value: 0.65 },
      { time: '18:00', value: 0.94 },
    ],
  },
  {
    id: 'SENS-PPG',
    name: 'Pulse Oximeter & Heart Rate',
    model: 'MAX30102 PPG Module',
    type: 'vitals',
    value: 78,
    unit: 'bpm (98% SpO2)',
    status: 'safe',
    zone: 'Wrist Cuff Sensor (Fleet Mean)',
    hardwareSpecs: 'Dual wavelength Red (660nm) & IR (880nm) with I2C digital FIFO buffer',
    trend: [
      { time: '17:15', value: 74 },
      { time: '17:30', value: 76 },
      { time: '17:45', value: 77 },
      { time: '18:00', value: 78 },
    ],
  },
  {
    id: 'SENS-ENV-DHT',
    name: 'Temperature & Humidity Sensor',
    model: 'DHT22 / AM2302',
    type: 'environment',
    value: '29.4°C / 76%',
    unit: 'Temp & RH',
    status: 'safe',
    zone: 'Underground Gallery Ambient',
    hardwareSpecs: 'Capacitive humidity sensor + thermistor with calibrated 1-wire digital output',
    trend: [
      { time: '17:15', value: 28.6 },
      { time: '17:30', value: 29.0 },
      { time: '17:45', value: 29.2 },
      { time: '18:00', value: 29.4 },
    ],
  },
  {
    id: 'SENS-DUST-PM',
    name: 'Laser Dust Particulate',
    model: 'PMS5003 Laser Counter',
    type: 'environment',
    value: 34.2,
    unit: 'µg/m³ PM2.5',
    status: 'safe',
    zone: 'Intake Airway (Mean)',
    hardwareSpecs: 'Laser scattering principle, 0.3 to 10 µm size resolution, UART interface',
    trend: [
      { time: '17:15', value: 26.0 },
      { time: '17:30', value: 31.2 },
      { time: '17:45', value: 38.5 },
      { time: '18:00', value: 34.2 },
    ],
  },
  {
    id: 'SENS-RAD-GM',
    name: 'Geiger-Müller Radiation Tube',
    model: 'SBM-20 Hard Beta/Gamma',
    type: 'radiation',
    value: '0.22 µSv/h (26 CPM)',
    unit: 'Dosimetry',
    status: 'safe',
    zone: 'Mineral Strata Incline',
    hardwareSpecs: '400V bias voltage, detection sensitivity ~22 CPM/µR/h (Co-60)',
    trend: [
      { time: '17:15', value: 0.18 },
      { time: '17:30', value: 0.20 },
      { time: '17:45', value: 0.21 },
      { time: '18:00', value: 0.22 },
    ],
  },
  {
    id: 'SENS-LOC-UWB',
    name: 'Sub-Surface Positioning Anchor',
    model: 'Decawave DWM1000 UWB',
    type: 'location',
    value: '8 Nodes Active',
    unit: '±0.25m Precision',
    status: 'safe',
    zone: 'Sub-surface Mesh Datum',
    hardwareSpecs: 'IEEE 802.15.4-2011 UWB, Channel 5 (6.5 GHz), Two-Way Ranging (TWR)',
    trend: [
      { time: '17:15', value: 99 },
      { time: '17:30', value: 98 },
      { time: '17:45', value: 99 },
      { time: '18:00', value: 100 },
    ],
  },
];

export const initialAlerts: SafetyAlert[] = [
  {
    id: 'ALT-101',
    title: 'H2S Toxic Gas Danger',
    workerName: 'Manoj Yadav',
    workerId: 'W1028',
    jacketId: 'SJ-005',
    zone: 'Level 4 - Sump & Drainage',
    severity: 'critical',
    timestamp: '1m ago',
    message: 'High gas level detected! Evacuate area immediately.',
    acknowledged: false,
  },
  {
    id: 'ALT-102',
    title: 'Tachycardia & Heat Stress Warning',
    workerName: 'Sunil Sharma',
    workerId: 'W1025',
    jacketId: 'SJ-002',
    zone: 'Tunnel 2 - Heading East',
    severity: 'warning',
    timestamp: '4m ago',
    message: 'High heart rate and high temperature warning.',
    acknowledged: false,
  },
  {
    id: 'ALT-103',
    title: 'Elevated PM2.5 Dust Particulate',
    workerName: 'Deepak Soren',
    workerId: 'W1030',
    jacketId: 'SJ-007',
    zone: 'Shaft 5 - Rock Bolt Decline',
    severity: 'warning',
    timestamp: '8m ago',
    message: 'High dust level detected in work zone.',
    acknowledged: true,
  },
  {
    id: 'ALT-104',
    title: 'Sub-surface Mesh Health Nominal',
    workerName: 'Alok Mukherjee',
    workerId: 'W1027',
    jacketId: 'SJ-004',
    zone: 'Shaft 1 - Main Intake Drift',
    severity: 'info',
    timestamp: '14m ago',
    message: 'All worker safety jackets are connected and clear.',
    acknowledged: true,
  },
];
