import { WorkerTelemetry, HardwareSensor, SafetyAlert } from '@/types/telemetry';

// No sample workers: workers appear when a real smart jacket connects
export const initialWorkers: WorkerTelemetry[] = [];

export const initialSensors: HardwareSensor[] = [
  {
    id: 'SENS-H2S-E',
    name: 'H2S Electronic Sensor',
    model: 'SPEC 3SP_H2S_50',
    type: 'gas',
    value: 11.8,
    unit: 'ppm',
    status: 'critical',
    zone: 'Level 4 - Sump (SJ-005)',
    hardwareSpecs: 'Range 0-50 ppm, Resolution 0.01 ppm, Response < 15s (Amperometric Gas Sensor)',
    trend: [
      { time: '17:15', value: 2.1 },
      { time: '17:30', value: 4.8 },
      { time: '17:45', value: 8.2 },
      { time: '18:00', value: 11.8 },
    ],
  },
  {
    id: 'SENS-H2S-OPT',
    name: 'Colorimetric H2S Strip + Camera',
    model: 'OV2640 Optical Strip Analyzer',
    type: 'gas',
    value: 'Positive (Darkened Stain)',
    unit: 'PbAc Optical Index',
    status: 'critical',
    zone: 'Chest Lapel Array (SJ-005)',
    hardwareSpecs: 'Lead Acetate paper test with ESP32-CAM optical HSV colorimetric verification',
    trend: [
      { time: '17:15', value: 0.05 },
      { time: '17:30', value: 0.22 },
      { time: '17:45', value: 0.65 },
      { time: '18:00', value: 0.94 },
    ],
  },
  {
    id: 'SENS-PPG',
    name: 'Pulse Oximeter & Heart Rate',
    model: 'MAX30102 PPG Module',
    type: 'vitals',
    value: 78,
    unit: 'bpm (98% SpO2)',
    status: 'safe',
    zone: 'Wrist Cuff Sensor (Fleet Mean)',
    hardwareSpecs: 'Dual wavelength Red (660nm) & IR (880nm) with I2C digital FIFO buffer',
    trend: [
      { time: '17:15', value: 74 },
      { time: '17:30', value: 76 },
      { time: '17:45', value: 77 },
      { time: '18:00', value: 78 },
    ],
  },
  {
    id: 'SENS-ENV-DHT',
    name: 'Temperature & Humidity Sensor',
    model: 'DHT22 / AM2302',
    type: 'environment',
    value: '29.4°C / 76%',
    unit: 'Temp & RH',
    status: 'safe',
    zone: 'Underground Gallery Ambient',
    hardwareSpecs: 'Capacitive humidity sensor + thermistor with calibrated 1-wire digital output',
    trend: [
      { time: '17:15', value: 28.6 },
      { time: '17:30', value: 29.0 },
      { time: '17:45', value: 29.2 },
      { time: '18:00', value: 29.4 },
    ],
  },
  {
    id: 'SENS-DUST-PM',
    name: 'Laser Dust Particulate',
    model: 'PMS5003 Laser Counter',
    type: 'environment',
    value: 34.2,
    unit: 'µg/m³ PM2.5',
    status: 'safe',
    zone: 'Intake Airway (Mean)',
    hardwareSpecs: 'Laser scattering principle, 0.3 to 10 µm size resolution, UART interface',
    trend: [
      { time: '17:15', value: 26.0 },
      { time: '17:30', value: 31.2 },
      { time: '17:45', value: 38.5 },
      { time: '18:00', value: 34.2 },
    ],
  },
  {
    id: 'SENS-RAD-GM',
    name: 'Geiger-Müller Radiation Tube',
    model: 'SBM-20 Hard Beta/Gamma',
    type: 'radiation',
    value: '0.22 µSv/h (26 CPM)',
    unit: 'Dosimetry',
    status: 'safe',
    zone: 'Mineral Strata Incline',
    hardwareSpecs: '400V bias voltage, detection sensitivity ~22 CPM/µR/h (Co-60)',
    trend: [
      { time: '17:15', value: 0.18 },
      { time: '17:30', value: 0.20 },
      { time: '17:45', value: 0.21 },
      { time: '18:00', value: 0.22 },
    ],
  },
  {
    id: 'SENS-LOC-UWB',
    name: 'Sub-Surface Positioning Anchor',
    model: 'Decawave DWM1000 UWB',
    type: 'location',
    value: '8 Nodes Active',
    unit: '±0.25m Precision',
    status: 'safe',
    zone: 'Sub-surface Mesh Datum',
    hardwareSpecs: 'IEEE 802.15.4-2011 UWB, Channel 5 (6.5 GHz), Two-Way Ranging (TWR)',
    trend: [
      { time: '17:15', value: 99 },
      { time: '17:30', value: 98 },
      { time: '17:45', value: 99 },
      { time: '18:00', value: 100 },
    ],
  },
];

// No sample alerts: alerts are raised from real jacket readings
export const initialAlerts: SafetyAlert[] = [];
